### ISSUE TITLE
About the comparision in your paper

### ISSUE THREAD

**Issue by gdwei** [chenxuluo/OriNet-demo#3]
In your paper, you said,
 "Note that [23] also use 2D data during training and camera parameters during
testing.."
[23] Xiao Sun, Jiaxiang Shang, Shuang Liang, and YichenWei. Compositional human pose
regression. ICCV, 2017.

But I can not find any description in [23] that indicates the use of camera parameters during
testing, could you help pointing out? Thanks.

**Comment by chenxuluo** [comment]
You can find it in the second paragraph on Page 5, "Note that the xy part and z part variables have different dimensions. xy is in image coordinate frame and the unit is in pixel. z is in camera coordinate frame and the unit is metric (millimeters in our case). This is no problem. During training, they are appropriately normalized (Eq.(8), Eq.(1)) or unnormalized (Eq.(6), Eq.(2)). During inference, in order to recover the 3D metric coordinates, the xy part is backprojected into camera space using known camera intrinsic parameters and a perspecitive projection model."

**Comment by gdwei** [comment]
Thanks!
